### ISSUE TITLE
[discussion] Proxy/getter approach

### ISSUE THREAD

**Issue by ivancuric** [Albert-Gao/auto-zustand-selectors-hook#1]
I was wondering if it would be possible to access the store properties with `useStore.use.bears` instead of having to call the selector — `useStore.use.bears()`. Would probably require proxies, but I'm not 100% sure.

**Comment by Albert-Gao** [comment]
this is a pretty good question, I initially wrote it like that, the currently problem is, we are building the selectors outside of React component, so if you do not wrap them, you will get the error of `not calling hook inside of a component`

may I know which problem you want solve?
or what concerns you of this approach?

**Comment by ivancuric** [comment]
Simply ergonomics, nothing else. 🤷‍♂️ It also makes the syntax highlighting look a bit weird and harder to distinguish since every property is a function, compared to the previous callback approach. Not sure if anything can be done there.
