### ISSUE TITLE
Can't mock stores using createSelectorFunctions

### ISSUE THREAD

**Issue by laytong** [Albert-Gao/auto-zustand-selectors-hook#11]
When following the zustand docs for mocking and resetting stores, it fails with a type error 

https://docs.pmnd.rs/zustand/guides/testing

TypeError: Cannot set properties of undefined (setting 'use')

presumably there's somewhere in

export const create = (<T>() => {
  console.log('zustand create mock');

  return (stateCreator: zustand.StateCreator<T> & ZustandFuncSelectors<T>) => {
    const store = actualCreate(stateCreator);
    console.log(stateCreator);
    const initialState = store.getState();
    storeResetFns.add(() => {
      store.setState(initialState, true);
    });
    return store;
  };
}) as typeof zustand.create;

where I need add ZustandFuncSelectors but I haven't been able to figure it out

**Comment by laytong** [comment]
Initially I had an issue with my vitest mocks not getting picked up, but this developed into 

`TypeError: t.getState is not a function`

I managed to get it to work, but interestingly it only seems to work with the following instantiation 

```ts
export const createPageStore = create<PageState & Actions>()(
  immer<PageState & Actions>((set) => ({
  /// your state and actions
 })
);
```
whereas the following (which works perfectly fine outside of tests)
```ts
export const createPageStore = create(
  immer<PageState & Actions>((set) => ({
  /// your state and actions
 })
);
```
throws the error

**Comment by laytong** [comment]
I'll leave it up to you to decide if this needs investigation or should be closed

**Comment by Albert-Gao** [comment]
Sorry for the super delayed response,

1. is this an type error or runtime error, seems only type error to me?
1. according to [zustand doc](https://github.com/pmndrs/zustand?tab=readme-ov-file#typescript-usage), when use with middleware, the type of the store should be provided from the very top one:

```typescript
// put the type BearState from the top level
const useBearStore = create<BearState>()(
  devtools(
    persist(
      (set) => (// implementation),
      {
        name: 'bear-storage',
      },
    ),
  ),
)
```

And it works with this lib, I have a test to reproduce it :)
https://github.com/Albert-Gao/auto-zustand-selectors-hook/blob/master/tests/middlewares.test.tsx

close it for now, please reopen if the problem persists :)
